name: cd

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Install goose for database migration
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Build notely binary
        run: scripts/buildprod.sh

      - name: Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>=363.0.0'

      - name: Build and push notely Docker image to Artifact Registry
        # FIXME we should increment TAG programatically (also applies to next step)
        run: gcloud builds submit --tag us-east1-docker.pkg.dev/notely-441419/notely-ar-repo/notely:1 .

      - name: Migrate database
        run: scripts/migratep.sh

      - name: Deploy notely image to Cloud Run
        run: |
          gcloud run deploy notely \
          --image us-east1-docker.pkg.dev/notely-441419/notely-ar-repo/notely:1 \
          --region us-east1 \
          --allow-unauthenticated \
          --project notely-441419 \
          --max-instances 4
